enum PROTOCOLS {
  // Built in Socket Events
  CONNECT = "connect",
  DISCONNECT = "disconnect",
  ON_ERROR = "error",
  // Custom Events
  JOIN_ROOM = "SOCKET/JOIN_ROOM",
  SERVER_TO_CLIENT_MSG = "SOCKET/SERVER_TO_CLIENT_MSG",
  CLIENT_TO_SERVER_MSG = "SOCKET/CLIENT_TO_SERVER_MSG",
  ROOM_DATA = "SOCKET/ROOM_DATA",
  RECEIVE_ROOM_DATA = "SOCKET/RECEIVE_ROOM_DATA",
  SEND_MESSAGE = "SOCKET/SEND_MESSAGE",
  ROOM_CONNECT = "SOCKET/ROOM_CONNECT",
  // NEW EVENTS
  UPDATE_ROOM_USER = "SOCKET/UPDATE_ROOM_USER",
  UPDATE_ROOM_MESSAGE = "SOCKET/UPDATE_ROOM_MESSAGE",
  CLIENT_TO_SERVER_DRAW = "SOCKET/CLIENT_TO_SERVER_DRAW",
  SERVER_TO_CLIENT_DRAW = "SOCKET/SERVER_TO_CLIENT_DRAW",
  UPDATE_PAINT= "SOCKET/UPDATE_PAINT",
  SOCKET_SERVER_ERROR= "SOCKET/SOCKET_SERVER_ERROR",
}

export default PROTOCOLS;